name: Flatpak Composite Action
description: Composite action for building Flatpak package
inputs:
  rclone-config:
    description: Base64 encoded Rclone config file
    required: true
  gpg-key:
    description: Base64 encoded GnuPG key pair
    required: true
runs:
  using: composite
  steps:
    - name: Setup environment
      run: |
        sudo add-apt-repository --yes ppa:flatpak/stable
        sudo apt update
        sudo apt install --yes flatpak flatpak-builder gnupg rclone
        sudo flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      shell: bash
    - name: Get runtime name
      id: runtimeName
      uses: mikefarah/yq@master
      with:
        cmd: yq '.runtime' "$APP/$APP.yml"
    - name: Get runtime version
      id: runtimeVersion
      uses: mikefarah/yq@master
      with:
        cmd: yq '.runtime-version' "$APP/$APP.yml"
    - name: Get base name
      id: baseName
      uses: mikefarah/yq@master
      with:
        cmd: yq '.base' "$APP/$APP.yml"
    - name: Get base version
      id: baseVersion
      uses: mikefarah/yq@master
      with:
        cmd: yq '.base-version' "$APP/$APP.yml"
    - name: Get extension names
      id: extensionNames
      uses: mikefarah/yq@master
      with:
        cmd: yq --csv-separator=' ' --output-format=csv '.sdk-extensions' "$APP/$APP.yml"
    - name: Get sdk name
      id: sdkName
      uses: mikefarah/yq@master
      with:
        cmd: yq '.sdk' "$APP/$APP.yml"
    - name: Install runtime and sdk
      env:
        RUNTIME_NAME: ${{ steps.runtimeName.outputs.result }}
        RUNTIME_VERSION: ${{ steps.runtimeVersion.outputs.result }}
        SDK_NAME: ${{ steps.sdkName.outputs.result }}
        BASE_NAME: ${{ steps.baseName.outputs.result }}
        BASE_VERSION: ${{ steps.baseVersion.outputs.result }}
        EXTENSION_NAMES: ${{ steps.extensionNames.outputs.result }}
      working-directory: ${{ env.APP }}
      run: |
        sudo flatpak install --assumeyes "$RUNTIME_NAME//$RUNTIME_VERSION" "$SDK_NAME//$RUNTIME_VERSION"
        if [ "$BASE_NAME" != 'null' ]; then
            sudo flatpak install --assumeyes "$BASE_NAME//$BASE_VERSION"
        fi
        GET_EXTENSION_VERSION=$(cat << EOF
        import configparser
        import sys
        
        config = configparser.ConfigParser(strict=False)
        config.read_file(sys.stdin)
        
        print(config["Extension org.freedesktop.Platform.GL"]["versions"].split(";")[0])
        EOF
        )
        if [ "$EXTENSION_NAMES" != 'null' ]; then
            EXTENSION_VERSION="$(flatpak info --show-metadata "$RUNTIME_NAME//$RUNTIME_VERSION" | python3 -c "$GET_EXTENSION_VERSION")"
            for i in $EXTENSION_NAMES; do
                sudo flatpak install --assumeyes "$i//$EXTENSION_VERSION"
            done
        fi
      shell: bash
    - name: Build Flatpak bundle
      working-directory: ${{ env.APP }}
      run: |
        mkdir -p bundle-dir
        flatpak-builder build-dir "$APP.yml"
        flatpak build-export export-dir build-dir
        flatpak build-bundle export-dir "bundle-dir/$APP.flatpak" "$APP"
      shell: bash
    - name: Setup Rclone configuration
      env:
        RCLONE_CONFIG: ${{ inputs.rclone-config }}
      run: base64 -d <<< "$RCLONE_CONFIG" > "$RCLONE_CONFIG_PATH"
      shell: bash
    - name: Publish Flatpak bundle
      working-directory: ${{ env.APP }}
      run: rclone --verbose --config "$RCLONE_CONFIG_PATH" copy "bundle-dir/$APP.flatpak" 'storage:flatpakbundle'
      shell: bash
    - name: Setup GnuPG configuration
      env:
        GPG_KEY: ${{ inputs.gpg-key }}
      run: |
        base64 -d <<< "$GPG_KEY" > flatpak.gpg
        gpg --import flatpak.gpg
        rm -f flatpak.gpg
      shell: bash
    - name: Sync Flatpak bundle
      working-directory: ${{ env.APP }}
      run: rclone --verbose --config "$RCLONE_CONFIG_PATH" sync 'storage:flatpakbundle' 'bundle-dir'
      shell: bash
    - name: Build Flatpak repository
      working-directory: ${{ env.APP }}
      run: |
        ostree init --mode 'archive' --repo 'repository-dir'
        find bundle-dir -name '*.flatpak' -exec flatpak build-import-bundle --gpg-sign "$GPG_KEY_ID" 'repository-dir' {} \;
      shell: bash
    - name: Publish Flatpak repository
      working-directory: ${{ env.APP }}
      run: |
        rclone --verbose --config "$RCLONE_CONFIG_PATH" --transfers 16 sync 'repository-dir' 'storage:flatpak'
      shell: bash
