name: Flatpak CI

on:
  push:
    paths:
      - '.github/actions/flatpak/action.yml'
      - '.github/workflows/net.sourceforge.Munt.yml'
      - 'net.sourceforge.Munt/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      APP: net.sourceforge.Munt
      GPG_KEY_ID: ${{ secrets.FLATPAK_GPG_KEY_ID }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Flatpak package
        uses: ./.github/actions/flatpak
        with:
          gpg-key: ${{ secrets.FLATPAK_GPG_KEY }}
          rclone-config: ${{ secrets.FLATPAK_RCLONE_CONFIG }}
